### ISSUE TITLE
Question about Project 1.5: Percolation

### ISSUE THREAD

**Issue by parkma99** [CS61BR/website_fa22#1]
are the row and column indices  integers between 0 and N − 1 ?

**Comment by sberkun** [comment]
yup, row is between 0 and (height-1) and col is between 0 and (width-1)

**Comment by parkma99** [comment]
thanks!!
By the way, do you have any plan about "gitlet" rust version?

**Comment by sberkun** [comment]
Maybe next semester, I'm still trying to finish making the assignments from [CS61B Fall 2022](https://fa22.datastructur.es/) right now. Once I finish the website and the autograders for these assignments, I'll start adding more (like gitlet and bearmaps). Gitlet is a cool project though, will definitely make it a priority.
